# Generated by Django 5.1.7 on 2025-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDroneCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_date', models.DateField(help_text='Enter the campaign date (e.g., use the first day of the month).')),
                ('image', models.ImageField(upload_to='monthly_drone_campaign_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monthly Drone Campaign',
                'verbose_name_plural': 'Monthly Drone Campaigns',
                'ordering': ['-campaign_date'],
            },
        ),
    ]
