# Generated by Django 5.1.7 on 2025-03-25 12:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('treeid', models.AutoField(primary_key=True, serialize=False)),
                ('pointname', models.CharField(blank=True, max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('dateplanted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TreeStatus',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('commonname', models.CharField(max_length=100)),
                ('localname', models.CharField(blank=True, max_length=100, null=True)),
                ('scientificname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uses', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='trees.tree')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.treestatus'),
        ),
        migrations.CreateModel(
            name='PlantingHole',
            fields=[
                ('holeid', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.treestatus')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='treetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.treetype'),
        ),
    ]
